### ISSUE TITLE
Short solution needed: "How to iterate Numpy array in loop" (python-numpy)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#1245]
Please help us write most modern and shortest code solution for this issue:
**How to iterate Numpy array in loop** (technology: [python-numpy](https://onelinerhub.com/python-numpy))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by ez-sherlock** [comment]
`import numpy as np`
`someArray = np.array([[1,2,3,4],[5,6,7,8]])`
`for i in someArray.flat: print(i)`

**Comment by ez-sherlock** [comment]
I added the solution please have a look :)

**Comment by nonunicorn** [comment]
[How to iterate Numpy array in loop](https://onelinerhub.com/python-numpy/how-to-iterate-numpy-array-in-loop)
