### ISSUE TITLE
Short solution needed: "Get array min" (python-numpy)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#1265]
Please help us write most modern and shortest code solution for this issue:
**Get array min** (technology: [python-numpy](https://onelinerhub.com/python-numpy))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by ez-sherlock** [comment]
Please assign this to me. I can write the shortest and readable python code of it :)

**Comment by nonunicorn** [comment]
[Get array min](https://onelinerhub.com/python-numpy/get-array-min)
