### ISSUE TITLE
Short solution needed: "How to use multiple conditions in where" (python-numpy)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#1281]
Please help us write most modern and shortest code solution for this issue:
**How to use multiple conditions in where** (technology: [python-numpy](https://onelinerhub.com/python-numpy))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by niklastoe** [comment]
`np.where(condition1 & condition2)`

You can add more than two conditions or use other operators such as `|` (or), `^` (exclusive or).

example:
import numpy as np
array = np.arange(0, 100).reshape(10,10)
condition1 = array > 15
condition2 = array < 25

print(np.where(condition1 & condition2))
print(array[np.where(condition1 & condition2)])

**Comment by nonunicorn** [comment]
Thanks a lot!
