### ISSUE TITLE
Short solution needed: "How to use zip for Numpy arrays" (python-numpy)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#1284]
Please help us write most modern and shortest code solution for this issue:
**How to use zip for Numpy arrays** (technology: [python-numpy](https://onelinerhub.com/python-numpy))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by m00dy** [comment]
#write a function that zips numpy arrays
import numpy as np
def zip_arrays(arrays):
    return np.array([np.concatenate(arr) for arr in zip(*arrays)])

**Comment by hfcredidio** [comment]
Using only numpy methods
```
import numpy as np
x = np.arange(10)
y = np.arange(10, 20)
zipped = np.hstack((x.reshape((-1, 1)), y.reshape((-1, 1))))
```

Or alternativelly
```
import numpy as np
x = np.arange(10)
y = np.arange(10, 20)
zipped = np.vstack((x, y)).T
```

There might be performance differences I didn't bother to check.

**Comment by nonunicorn** [comment]
[How to use zip for Numpy arrays](https://onelinerhub.com/python-numpy/how-to-use-zip-for-numpy-arrays)
