### ISSUE TITLE
Short solution needed: "How to change nan values to 0" (python-pandas)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#1349]
Please help us write most modern and shortest code solution for this issue:
**How to change nan values to 0** (technology: [python-pandas](https://onelinerhub.com/python-pandas))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by ez-sherlock** [comment]
Please assign this to me. Thanks.

**Comment by nonunicorn** [comment]
[How to change nan values to 0](https://onelinerhub.com/python-pandas/how-to-change-nan-values-to-0)
