### ISSUE TITLE
Short solution needed: "How to get unique values" (python-pandas)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#1352]
Please help us write most modern and shortest code solution for this issue:
**How to get unique values** (technology: [python-pandas](https://onelinerhub.com/python-pandas))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by codelover96** [comment]
Unique values in a specific data structure like a Data Frame; Or just in a column?

**Comment by nonunicorn** [comment]
Better if you give both solutions

**Comment by nonunicorn** [comment]
[How to get unique values](https://onelinerhub.com/python-pandas/how-to-get-unique-values)

**Comment by codelover96** [comment]
```unique()``` function works for either a Pandas Series or Pandas DataFrame. The difference being, for a DataFrame, you have to pass the index of the column. That's because ```unique()``` function accepts a 1D array, like a Pandas Series.

PS. it's faster than numpy.unique()
API reference: [pandas.unique](https://pandas.pydata.org/docs/reference/api/pandas.unique.html)

**Comment by codelover96** [comment]
# Get unique values of a Serie
```python
import pandas as pd

my_list = [10, 100, 100, 10, 1, 1000]
my_serie = pd.Series(my_list)

print("My serie")
print(my_serie)

print("Unique values:")
print(pd.unique(my_serie))
```

- `import pandas as pd` - load [lib:Pandas module](/python-pandas/how-to-install-pandas)
- `my_list` - declare a python list and assign values
- `df = pd.Series(my_list)` - constructing a Serie using pandas
- `print(pd.unique(my_serie)` - unique() returns unique values of a one-dimensional array, like a Serie

## Output:
```
my_serie
0      10
1     100
2     100
3      10
4       1
5    1000
dtype: int64
Unique values:
[  10  100    1 1000]

````
# One line solution
```python
print(pd.Series([2, 1, 3, 3]).unique())
```
## Output
[2 1 3]

# Get unique values of a DataFrame column
```python
import pandas as pd

phoneReviewsSet = {
  'Phone': ['iPhone 5', 'iPhone 6', 'iPhone8', 'Galaxy S9', 'Galaxy Note 10'],
  'Stars': [1/5, 4/5, 3/5, 4/5, 5/5],
  'Phone Price': [204, 320, 501, 800, 990]
}

df = pd.DataFrame(phoneDataSet)
print(df)
print(df["Phone"].unique())

```
# Advanced: Return unique values from all columns in a DataFrame
You would have to traverse all columns of the DataFrame and call the ```unique()``` function for each one. Or you could use ```drop_dublicates()``` function to return the distinct rows of a DataFrame

**Comment by nonunicorn** [comment]
Thanks man!

Deployed here:
https://onelinerhub.com/python-pandas/how-to-get-unique-values-from-series

Dataframe solution already deployed:
https://onelinerhub.com/python-pandas/how-to-get-unique-values
