### ISSUE TITLE
Short solution needed: "How to plot data frame" (python-pandas)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#1378]
Please help us write most modern and shortest code solution for this issue:
**How to plot data frame** (technology: [python-pandas](https://onelinerhub.com/python-pandas))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by bdrum** [comment]
Hi!

In fact plotting in pandas based on backend engine. The last one by default is matplotlib, but also could be a seaborn and other...So it will change arguments of plotting functions.

Moreover visualizations of data itself always depends from a task.

E.g. you have a dataframe with two normally distributed values:
```python
a = {'a': np.random.normal(0,1,100), 'b' : np.random.normal(1,2,100)}
df = pd.DataFrame.from_dict(a)
```

In this case there is a many ways that you want to see:

Just plot them as they are:

```python
df.plot()
```
![plot](https://user-images.githubusercontent.com/16210997/160394129-99e00e3f-97ab-451c-8357-e40600f2befa.png)

Plotting histogram on different axes:
```python
df.hist()
```
![hist](https://user-images.githubusercontent.com/16210997/160394250-a9507f2b-f850-4fe8-9c94-0e2bc13d09d7.png)

Comparing the data via histogramming into one plot:

```python
df.plot.hist()
```
![plot hist](https://user-images.githubusercontent.com/16210997/160394569-bca93e7e-760c-4928-afe4-8c440536980d.png)

So in this context  I'm not sure what does it mean "How to plot data frame?"

**Comment by nonunicorn** [comment]
[How to plot data frame](https://onelinerhub.com/python-pandas/how-to-plot-data-frame)

**Comment by nonunicorn** [comment]
Thanks a lot man!

Deployed into 3 code examples:
- https://onelinerhub.com/python-pandas/how-to-plot-data-frame
- https://onelinerhub.com/python-pandas/how-to-plot-data-frame-as-histogram-bars-chart
- https://onelinerhub.com/python-pandas/how-to-draw-overlay-data-frame-bar-charts
