### ISSUE TITLE
Short solution needed: "How to create pivot table from data frame" (python-pandas)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#1379]
Please help us write most modern and shortest code solution for this issue:
**How to create pivot table from data frame** (technology: [python-pandas](https://onelinerhub.com/python-pandas))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by shashank2325** [comment]
We can create Pivot tables by using this command : **pd.pivot_table(df , index=['column1','column2'])**
You can add how many columns you want. df is your dataframe.

**Comment by nonunicorn** [comment]
[How to create pivot table from data frame](https://onelinerhub.com/python-pandas/how-to-create-pivot-table-from-data-frame)
