### ISSUE TITLE
The f..ck is this?

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#1513]
https://onelinerhub.com/ubuntu/how-to-change-timezone-in-cli

**Comment by RithyaReddy** [comment]
Do we need to create pull request to solve this bug ?
Can you please explain the process to solve the bug

**Comment by nonunicorn** [comment]
Well, this code is wrong and I was too lazy to describe everything in detail, sorry :)
This code shows timezone rather than allows to change it, so we need correct code here.

One way is to directly fix [the file](https://github.com/Onelinerhub/onelinerhub/blob/main/ubuntu/how-to-change-timezone-in-cli.md) and create pull request. Other way - is to write the correct solution right in this issue comment and I'll deploy that to the right place.

Thanks!

**Comment by nonunicorn** [comment]
Fixed: https://onelinerhub.com/ubuntu/how-to-change-timezone-in-cli
