### ISSUE TITLE
Short solution needed: "Using hashmap in Rust" (rust)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#1928]
Please help us write most modern and shortest code solution for this issue:
**Using hashmap in Rust** (technology: [rust](https://onelinerhub.com/rust))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create [pull request](https://github.com/Onelinerhub/onelinerhub/blob/main/how-to-contribute.md) with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to [use comments](https://github.com/Onelinerhub/onelinerhub/blob/main/how-to-contribute.md#code-file-md-format) explain solution.
3. Link to this issue in comments of pull request.

**Comment by devmalik7** [comment]
I would like to work on this issue. Please assign me this issue

**Comment by nonunicorn** [comment]
> I would like to work on this issue. Please assign me this issue

Thanks, this is now processed by a small team of coders. But we would like to get more help soon, as we're ready with an updated process for that. I'll update README once we're ready.
