### ISSUE TITLE
Flicker appears when hover over a keyword

### ISSUE THREAD

**Issue by sulmar** [Onelinerhub/onelinerhub#1975]
When you hover over a keyword near the line, an unpleasant flicker appears. 
I also noticed that it generates an error, which you can see in the console.
`client.js?36:21 Error: <svg> attribute viewBox: Expected number, "x1=".`

## Links and notes
- https://onelinerhub.com/redis/auth-by-password-in-redis

**Comment by nonunicorn** [comment]
Thanks, we'll switch to new line-drawing component soon.

**Comment by nonunicorn** [comment]
Can you please check now?
