### ISSUE TITLE
"How to iterate enum in Rust" is not valid Rust

### ISSUE THREAD

**Issue by jasger9000** [Onelinerhub/onelinerhub#2000]
1. A link to the code with a problem: https://github.com/Onelinerhub/onelinerhub/blob/main//rust/how-to-iterate-enum-in-rust.md
2. Short explanation of the problem in the solution:
The code explains that ::iter() can be called on an enum variant, which is not true, an enum does not implement the method iter().
3. Proposal of changes (if any):
  - Remove the code example completely, as rust does not natively implement this behaviour
  - Implement and showcase a function that solves this problem
  - Make use of a crate like [strum](https://crates.io/crates/strum) which adds a derive statement to solve this problem

### Example
Here the compiler output with the example code from the linked problem:
```
error[E0599]: no variant or associated item named `iter` found for enum `Fruit` in the current scope
 --> r.rs:8:25
  |
1 | enum Fruit {
  | ---------- variant or associated item `iter` not found for this enum
...
8 |     for fruit in Fruit::iter() {
  |                         ^^^^ variant or associated item not found in `Fruit`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
```

**Comment by nonunicorn** [comment]
Fixed, I've just remove the invalid piece of code
