### ISSUE TITLE
Short solution needed: "How to clone a repository" (git)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#636]
Please help us write most modern and shortest code solution for this issue:
**How to clone a repository** (technology: [git](https://onelinerhub.com/git))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by RithyaReddy** [comment]
@nonunicorn 

git clone "mention the url"
for example 
$ git clone "https://github.com/RithyaReddy/onelinerhub.git"

**Comment by nonunicorn** [comment]
[How to clone a repository](https://onelinerhub.com/git/how-to-clone-a-repository)
