### ISSUE TITLE
Short solution needed: "How long is commit message allowed to be" (git)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#665]
Please help us write most modern and shortest code solution for this issue:
**How long is commit message allowed to be** (technology: [git](https://onelinerhub.com/git))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by RithyaReddy** [comment]
@nonunicorn 

- maximum is 72 characters

**Comment by nonunicorn** [comment]
[How long is commit message allowed to be](https://onelinerhub.com/git/how-long-is-commit-message-allowed-to-be)
