### ISSUE TITLE
Short solution needed: "How to copy to clipboard" (vim)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#789]
Please help us write most modern and shortest code solution for this issue:
**How to copy to clipboard** (technology: [vim](https://onelinerhub.com/vim))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by AimarIbarra** [comment]
Copying to clipboard in Vim can be done trough standard input, but I believe that it is easier to bind the method to "Ctrl + c" with a command (adding it to the .vimrc file is reccomended but not necessary).

Also, the Vim version the user is using must have the +clipboard feature; should this be explained alongside what should be done to implement it if it is missing?

**Comment by nonunicorn** [comment]
[How to copy to clipboard](https://onelinerhub.com/vim/how-to-copy-to-clipboard)
