### ISSUE TITLE
Short solution needed: "Get external IP in CLI" (ubuntu)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#930]
Please help us write most modern and shortest code solution for this issue:
**Get external IP in CLI** (technology: [ubuntu](https://onelinerhub.com/ubuntu))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by RithyaReddy** [comment]
@nonunicorn 
Sir I want to work on all this ubuntu related stuff
At Present I am interested and presently working on linux
So this acts like an exercise to me
Can I work on these issues?

**Comment by nonunicorn** [comment]
Sure, have sent you an invite to the repo, waiting for a confirmation from you before I can assign you to the Ubuntu issues.

**Comment by nonunicorn** [comment]
[Get external IP in CLI](https://onelinerhub.com/ubuntu/get-external-ip-in-cli)
