### ISSUE TITLE
Short solution needed: "How zip a folder in CLI" (ubuntu)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#950]
Please help us write most modern and shortest code solution for this issue:
**How zip a folder in CLI** (technology: [ubuntu](https://onelinerhub.com/ubuntu))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by RithyaReddy** [comment]
@nonunicorn 
I have solved all the issues assigned to me. If you don't mind can you please review and merge them ?

**Comment by nonunicorn** [comment]
Sure, within couple of day will do as we're focused on releasing updates on the platform itself at the moment.
Thank you!

**Comment by nonunicorn** [comment]
[How zip a folder in CLI](https://onelinerhub.com/ubuntu/how-zip-a-folder-in-cli)
