### ISSUE TITLE
Short solution needed: "How to control volume in CLI" (ubuntu)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#956]
Please help us write most modern and shortest code solution for this issue:
**How to control volume in CLI** (technology: [ubuntu](https://onelinerhub.com/ubuntu))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by RithyaReddy** [comment]
@nonunicorn 
install alsa and launch it
$ sudo apt-get install alsa-utils
$ alsamixer

then use
$ amixer scontrols

for example:
following command will set the volume on the Master control/property of the first sound card to 100%
$ amixer -c 0 set Master 100%

Sir one doubt, even I am solving good first issues, but why is it not reflecting on my digital resume?
