### ISSUE TITLE
New technology needs to be included

### ISSUE THREAD

**Issue by SrijithProDev-2612** [Onelinerhub/onelinerhub#960]
Hey everyone, 
This is to aware you all about an language that has been recently got people's attention- Rust Lang. I would request you all to create a new technology with the name Rust Lang so that the Rust community might get useful from Onelinerhub.

Thanks in advance :)

**Comment by nonunicorn** [comment]
Started Rust folder here: https://onelinerhub.com/rust

**Comment by SrijithProDev-2612** [comment]
Thanks!
