### ISSUE TITLE
Fix css code(s) that show stylesheets instead of code pages

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#973]
https://onelinerhub.com/html/include_css

**Comment by simplekind** [comment]
Hi @nonunicorn , do you want to display the output of the css code there?
I can work on it , can you assign it to me?

**Comment by nonunicorn** [comment]
Hi engineer :)

This is [UI](https://github.com/Onelinerhub/onelinerhub-ui) repo, I think that should be fixed inside Nginx configuration, not only backend scripts. Will you handle that?

**Comment by nonunicorn** [comment]
So this link: https://onelinerhub.com/html/include_css
Should actually render this code: https://github.com/Onelinerhub/onelinerhub/blob/main/html/include_css.md

**Comment by simplekind** [comment]
Hi @nonunicorn can you share the Nginx config repo sending this css code, I think there might be some issue in it like it might be sending code as plain text file instead of static file .

**Comment by nonunicorn** [comment]
Sorry, forgot to do, here's the config:

```
server {
  server_name onelinerhub.com;
  root /var/www/onelinerhub-ui/app/web;

  location ~ \.png$ {
    root /var/www/onelinerhub;
    expires max;
  }

  location ~ \.(woff|ttf|eof)$ {
    expires max;
  }

  location / {
    try_files $uri /index.php?$args;
  }

  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
  }
}
```
